local map = vim.keymap.set

-- Decriptions for keymaps
map({ 'n', 'v' }, '<leader>c', '', { desc = '+code' })
map({ 'n', 'v' }, '<leader>a', '', { desc = '+ai' })
map({ 'n', 'v' }, '<leader>f', '', { desc = '+find' })
map({ 'n', 'v' }, '<leader>g', '', { desc = '+git' })
map({ 'n', 'v' }, '<leader>u', '', { desc = '+ui' })
map({ 'n', 'v' }, '<leader>q', '', { desc = '+quit' })
map({ 'n', 'v' }, '<leader>T', '', { desc = '+toggles' })
map({ 'n', 'v' }, '<leader>s', '', { desc = '+search' })
map({ 'n', 'v' }, 'gr', '', { desc = '+LSP' })
map({ 'n', 'v' }, '<leader>b', '', { desc = '+buffers' })
map({ 'n', 'v' }, '<leader>d', '', { desc = '+debug' })
map({ 'n', 'v' }, '<leader>cr', '', { desc = '+refactor' })
map({ 'n', 'v' }, '<leader>N', '', { desc = '+notes' })
map({ 'n', 'v' }, '<leader>m', '', { desc = '+make snip' })
map({ 'n', 'v' }, '<leader>x', '', { desc = '+diagnostic' })
map({ 'n', 'v' }, '<leader>w', '', { desc = '+wtf' })
map({ 'n', 'v' }, '<leader>C', '', { desc = '+Cargo' })
map({ 'n', 'v' }, '<leader>z', '', { desc = '+Zoom' })
map({ 'n', 'v' }, '<leader>bs', '', { desc = '+sort buffer' })
