return {
  -- 'obsidian-nvim/obsidian.nvim',
  -- version = '*',
  -- ft = 'markdown',
  -- event = {
  --   'BufReadPre',
  -- },
  -- opts = {
  --   legacy_commands = false,
  --   workspaces = {
  --     {
  --       name = 'Main vault',
  --       path = '~/Documents/Obsidian Vault/',
  --     },
  --     {
  --       name = 'Random thoughts',
  --       path = '~/Documents/Random in my mind/',
  --     },
  --     {
  --       name = 'Notes',
  --       path = '~/Documents/Notes/',
  --     },
  --   },
  -- },
}
